import React, { useEffect, useMemo, useState } from 'react';
import { MapContainer, TileLayer, CircleMarker, Polygon, Popup, useMap } from 'react-leaflet';
import { Activity, AlertTriangle, Bell, BookOpen, CheckCircle2, CloudRain, Database, FileWarning, Layers, MapPin, Menu, Navigation, Radio, RefreshCw, Shield, Siren, Smartphone, TrendingUp, Users, X, Zap } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import FieldReporter from './FieldReporter';

const API = import.meta.env.VITE_API_URL || 'https://bhushakti-backend.onrender.com';

const DEMO_REGIONS = [
 {id:'GSI-AR-01',name:'Bhalukpong - Bomdila Corridor',district:'West Kameng',state:'Arunachal Pradesh',lat:27.2645,lng:92.4159,susceptibility:89,slope:46,elevation:2150,road:'NH-13',road_status:'CLOSED'},
 {id:'GSI-ML-01',name:'Cherrapunji - Mawsynram Escarpment',district:'East Khasi Hills',state:'Meghalaya',lat:25.2986,lng:91.5822,susceptibility:81,slope:38,elevation:1430,road:'SH-5',road_status:'RESTRICTED'},
 {id:'GSI-NL-01',name:'Pfutsero - Kohima Ridge',district:'Kohima',state:'Nagaland',lat:25.6751,lng:94.1086,susceptibility:76,slope:32,elevation:1444,road:'NH-29',road_status:'RESTRICTED'},
 {id:'GSI-MZ-01',name:'Sairang - Aizawl Syncline',district:'Aizawl',state:'Mizoram',lat:23.7271,lng:92.7176,susceptibility:84,slope:35,elevation:1132,road:'NH-54',road_status:'CLOSED'},
];
const riskScore = r => Math.min(100, Math.round(r.susceptibility*.45 + 90*.25 + 84*.15 + Math.min(r.slope/50*100,100)*.15));
const riskLevel = n => n>=75?'CRITICAL':n>=55?'HIGH':n>=35?'MODERATE':'LOW';
const riskClass = n => n>=75?'text-red-400':n>=55?'text-amber-400':'text-emerald-400';

function FlyTo({region}) { const map=useMap(); useEffect(()=>{map.flyTo([region.lat,region.lng],8,{duration:.8})},[region,map]); return null; }
function Stat({icon:Icon,label,value,sub,tone='cyan'}) { return <div className="panel p-3"><div className="flex items-center justify-between"><div><p className="muted uppercase tracking-widest text-[9px]">{label}</p><p className="text-xl font-black text-white mt-1">{value}</p><p className="muted text-[9px] mt-1">{sub}</p></div><div className={`p-2 rounded-lg bg-${tone}-500/10`}><Icon className={`w-4 h-4 text-${tone}-400`}/></div></div></div> }
function Badge({children,critical=false}) { return <span className={`px-2 py-1 rounded-md text-[9px] font-black tracking-wider ${critical?'bg-red-500/15 text-red-400 border border-red-500/30':'bg-cyan-500/10 text-cyan-300 border border-cyan-500/20'}`}>{children}</span> }

export default function App(){
 const [regions,setRegions]=useState(DEMO_REGIONS); const [selected,setSelected]=useState(DEMO_REGIONS[0]);
 const [incidents,setIncidents]=useState([]); const [summary,setSummary]=useState(null); const [tab,setTab]=useState('COMMAND');
 const [field,setField]=useState(false); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(true); const [lang,setLang]=useState('EN');
 const [siren,setSiren]=useState(false);

 const load=async()=>{setLoading(true); try{ const [r,s,i]=await Promise.all([fetch(`${API}/api/regions`),fetch(`${API}/api/dashboard/summary`),fetch(`${API}/api/incidents`)]); if(r.ok)setRegions(await r.json()); if(s.ok)setSummary(await s.json()); if(i.ok)setIncidents(await i.json()); setNotice('LIVE API CONNECTED'); }catch{setNotice('DEMO MODE · API UNAVAILABLE')} finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const score=useMemo(()=>riskScore(selected),[selected]); const level=riskLevel(score);
 const critical=regions.filter(r=>riskScore(r)>=75).length; const high=regions.filter(r=>riskScore(r)>=55&&riskScore(r)<75).length;
 const forecast=summary?.forecast||[{time:'00:00',rain:24,risk:32},{time:'04:00',rain:52,risk:48},{time:'08:00',rain:94,risk:69},{time:'12:00',rain:142,risk:86},{time:'16:00',rain:105,risk:78},{time:'20:00',rain:68,risk:59}];
 const logAction=async action=>{try{await fetch(`${API}/api/log-action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sector_name:selected.name,lat:selected.lat,lng:selected.lng,risk_score:score,action_triggered:action})})}catch{}};
 const triggerSiren=()=>{setSiren(true);logAction('EVACUATION_WARNING_TRIGGERED');setNotice('EVACUATION WARNING SENT · DEMO ACTION');if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`Warning. Landslide risk is ${score} percent at ${selected.name}. Follow evacuation instructions.`))}};
 const submitReport=rep=>{setIncidents(x=>[rep,...x]);setField(false);setSelected({id:rep.id,name:rep.sector_name||rep.name,district:rep.district||'Field Report',state:rep.state||'NER',lat:rep.lat,lng:rep.lng,susceptibility:Math.max(score,70),slope:selected.slope,elevation:selected.elevation,road:'Field observation',road_status:'REVIEW'});setNotice('FIELD REPORT RECEIVED · MAP UPDATED')};

 const tabs=[['COMMAND','Command'],['GIS','Live GIS'],['WARNING','Early Warning'],['INCIDENTS','Incidents'],['RESPONSE','Response'],['ANALYTICS','Analytics']];
 return <div className="h-screen w-screen overflow-hidden bg-[#050a13] text-slate-200 text-xs font-sans">
  {field&&<FieldReporter onBack={()=>setField(false)} onReportSubmitted={submitReport}/>} 
  {siren&&<div className="fixed inset-0 z-[3000] bg-red-950/90 backdrop-blur flex items-center justify-center p-6"><div className="max-w-md w-full text-center panel border-red-500 p-7"><div className="mx-auto w-16 h-16 rounded-full bg-red-500/20 flex items-center justify-center animate-pulse"><Siren className="w-8 h-8 text-red-400"/></div><h2 className="text-2xl font-black text-red-300 mt-4">EVACUATION WARNING</h2><p className="text-slate-300 mt-2">{selected.name}</p><p className="text-5xl font-black text-white mt-3">{score}<span className="text-xl">/100</span></p><p className="text-red-300 text-[10px] uppercase tracking-widest mt-2">Risk threshold exceeded</p><button onClick={()=>setSiren(false)} className="mt-6 px-5 py-2 bg-red-600 rounded-lg font-bold">ACKNOWLEDGE</button></div></div>}
  <header className="h-14 border-b border-slate-800 bg-[#080f1d] flex items-center justify-between px-4 gap-4">
   <div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 rounded-lg bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center"><Activity className="w-5 h-5 text-cyan-400"/></div><div className="min-w-0"><h1 className="font-black tracking-widest text-white text-sm">BHUSAKTHI</h1><p className="muted text-[8px] uppercase tracking-[.25em] truncate">AI Landslide Early Warning & Response · NER</p></div></div>
   <div className="hidden md:flex items-center gap-1">{tabs.map(([id,name])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-md text-[9px] font-bold uppercase tracking-wider ${tab===id?'bg-cyan-500/15 text-cyan-300':'text-slate-500 hover:text-white'}`}>{name}</button>)}</div>
   <div className="flex items-center gap-2"><button onClick={()=>setLang(lang==='EN'?'HI':'EN')} className="px-2 py-1 border border-slate-700 rounded text-[9px]">{lang}</button><span className={`hidden sm:flex items-center gap-1 text-[9px] ${notice.includes('UNAVAILABLE')?'text-amber-400':'text-emerald-400'}`}><span className="w-1.5 h-1.5 rounded-full bg-current animate-pulse"/>{notice||'CONNECTING'}</span><button onClick={load} className="p-2 hover:bg-slate-800 rounded"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>
  </header>
  <div className="md:hidden h-9 border-b border-slate-800 flex gap-1 overflow-x-auto px-2 items-center">{tabs.map(([id,name])=><button key={id} onClick={()=>setTab(id)} className={`px-2 py-1 text-[8px] whitespace-nowrap ${tab===id?'text-cyan-300 border-b border-cyan-400':'text-slate-500'}`}>{name}</button>)}</div>
  <main className="h-[calc(100vh-56px)] overflow-auto p-3 md:p-4">
   {tab==='COMMAND'&&<>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-2 mb-3"><Stat icon={AlertTriangle} label="Critical zones" value={critical} sub="Immediate attention" tone="red"/><Stat icon={TrendingUp} label="High risk zones" value={high} sub="Enhanced monitoring" tone="amber"/><Stat icon={FileWarning} label="Active incidents" value={incidents.filter(i=>i.status!=='RESOLVED').length||2} sub="Field + system reports"/><Stat icon={Radio} label="Sensors online" value={summary?.sensors_online||12} sub="Telemetry channels"/><Stat icon={Navigation} label="Roads impacted" value={summary?.roads_impacted||4} sub="Closed / restricted" tone="amber"/></div>
    <div className="grid xl:grid-cols-[1.6fr_1fr] gap-3">
     <section className="panel overflow-hidden"><div className="px-3 py-2 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold text-white">Regional Risk Map</h2><p className="muted text-[9px]">GIS risk layers · field observations · road connectivity</p></div><Badge>{regions.length} MONITORED ZONES</Badge></div><div className="h-[330px] md:h-[430px] relative"><MapContainer center={[25.7,92.8]} zoom={6} scrollWheelZoom className="h-full w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FlyTo region={selected}/>{regions.map(r=>{const s=r.risk_score??riskScore(r);return <React.Fragment key={r.id}><Polygon positions={[[r.lat+.12,r.lng-.12],[r.lat+.12,r.lng+.12],[r.lat-.12,r.lng+.12],[r.lat-.12,r.lng-.12]]} pathOptions={{color:s>=75?'#ef4444':s>=55?'#f59e0b':'#10b981',fillOpacity:.12,weight:1}}/><CircleMarker center={[r.lat,r.lng]} radius={s>=75?11:8} pathOptions={{color:s>=75?'#ef4444':s>=55?'#f59e0b':'#10b981',fillColor:s>=75?'#ef4444':s>=55?'#f59e0b':'#10b981',fillOpacity:.7}} eventHandlers={{click:()=>setSelected(r)}}><Popup><b>{r.name}</b><br/>Risk: {s}/100<br/>{r.road}: {r.road_status}</Popup></CircleMarker></React.Fragment>})}</MapContainer><div className="absolute top-3 left-3 z-[500] panel px-3 py-2 pointer-events-none"><p className="text-[8px] text-cyan-300 font-bold">LIVE GIS / RISK OVERLAY</p><p className="text-[8px] muted">OpenStreetMap base · demo risk fusion</p></div></div></section>
     <div className="space-y-3"><section className="panel p-4"><div className="flex justify-between"><div><p className="muted text-[9px] uppercase tracking-widest">Selected hazard zone</p><h2 className="text-base font-black text-white mt-1">{selected.name}</h2><p className="muted mt-1">{selected.district}, {selected.state}</p></div><Badge critical={score>=75}>{level}</Badge></div><div className="flex items-end gap-4 mt-5"><div><span className={`text-5xl font-black ${riskClass(score)}`}>{score}</span><span className="muted"> / 100</span></div><div className="flex-1 pb-2"><div className="h-2 bg-slate-800 rounded-full overflow-hidden"><div className="h-full bg-current rounded-full" style={{width:`${score}%`}}/></div><p className="muted text-[9px] mt-2">Weighted fusion of susceptibility, rainfall, moisture and slope.</p></div></div><div className="grid grid-cols-2 gap-2 mt-5"><div className="metric"><CloudRain className="w-3 h-3 text-cyan-400"/><b>135 mm</b><span>rainfall</span></div><div className="metric"><Zap className="w-3 h-3 text-amber-400"/><b>84%</b><span>soil moisture</span></div><div className="metric"><TrendingUp className="w-3 h-3 text-red-400"/><b>{selected.slope}°</b><span>slope</span></div><div className="metric"><Layers className="w-3 h-3 text-violet-400"/><b>{selected.elevation}m</b><span>elevation</span></div></div></section>
      <section className="panel p-3"><div className="flex justify-between items-center mb-2"><div><h3 className="font-bold text-white">Weather-linked risk forecast</h3><p className="muted text-[9px]">Next operational window</p></div><CloudRain className="w-4 h-4 text-cyan-400"/></div><div className="h-[150px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="time" tick={{fontSize:8,fill:'#64748b'}}/><YAxis domain={[0,100]} tick={{fontSize:8,fill:'#64748b'}}/><Tooltip contentStyle={{background:'#0b1424',border:'1px solid #243244',fontSize:10}}/><Line type="monotone" dataKey="risk" stroke="#22d3ee" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div></section>
      <div className="grid grid-cols-2 gap-2"><button onClick={triggerSiren} className="action danger"><Siren className="w-4 h-4"/>Issue warning</button><button onClick={()=>setField(true)} className="action"><Smartphone className="w-4 h-4"/>Field report</button></div></div>
    </div>
    <div className="grid lg:grid-cols-3 gap-3 mt-3"><section className="panel p-3"><h3 className="font-bold text-white mb-3">Emergency prioritisation</h3>{(summary?.priority||[{label:'Bhalukpong - Bomdila',score:92,action:'Evacuate / close corridor'},{label:'Sairang - Aizawl',score:83,action:'Deploy field team'},{label:'Cherrapunji - Mawsynram',score:76,action:'Traffic restriction'}]).map((x,i)=><div key={x.label} className="flex items-center gap-2 py-2 border-b border-slate-800 last:border-0"><span className="text-slate-600 font-mono">0{i+1}</span><div className="flex-1"><p className="font-semibold text-slate-200 text-[10px]">{x.label}</p><p className="muted text-[9px]">{x.action}</p></div><b className={riskClass(x.score)}>{x.score}</b></div>)}</section><section className="panel p-3"><h3 className="font-bold text-white mb-3">Connectivity</h3>{regions.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="w-full flex justify-between items-center py-2 border-b border-slate-800 last:border-0"><span className="text-left"><b className="text-[10px]">{r.road}</b><small className="block muted">{r.district}</small></span><span className={`text-[9px] font-black ${r.road_status==='CLOSED'?'text-red-400':'text-amber-400'}`}>{r.road_status}</span></button>)}</section><section className="panel p-3"><h3 className="font-bold text-white mb-3">Response readiness</h3><div className="space-y-3"><Ready label="Sensor network" value="12 / 12 online"/><Ready label="District coordination" value="READY"/><Ready label="Field reporting" value="GPS + media"/><Ready label="Warning channel" value="Browser demo"/></div></section></div>
   </>}
   {tab==='GIS'&&<div className="grid lg:grid-cols-[1fr_300px] gap-3"><section className="panel h-[calc(100vh-100px)] overflow-hidden"><MapContainer center={[25.7,92.8]} zoom={6} scrollWheelZoom className="h-full w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{regions.map(r=>{const s=r.risk_score??riskScore(r);return <CircleMarker key={r.id} center={[r.lat,r.lng]} radius={10} pathOptions={{color:s>=75?'#ef4444':s>=55?'#f59e0b':'#10b981',fillOpacity:.7}} eventHandlers={{click:()=>setSelected(r)}}><Popup>{r.name}<br/>Risk {s}/100</Popup></CircleMarker>})}</MapContainer></section><section className="space-y-2">{regions.map(r=><button onClick={()=>setSelected(r)} key={r.id} className={`panel p-3 w-full text-left ${selected.id===r.id?'border-cyan-500/50':''}`}><div className="flex justify-between"><b>{r.name}</b><span className={riskClass(riskScore(r))}>{riskScore(r)}</span></div><p className="muted mt-1">{r.state} · {r.road} · {r.road_status}</p></button>)}<div className="panel p-3"><p className="font-bold">Map layers</p><p className="muted mt-2">● Risk zones · ● Field reports · Road connectivity · Terrain/slope attributes</p></div></section></div>}
   {tab==='WARNING'&&<WarningPanel forecast={forecast} selected={selected} score={score} onWarn={triggerSiren}/>} 
   {tab==='INCIDENTS'&&<IncidentPanel incidents={incidents} onField={()=>setField(true)} onRefresh={load}/>} 
   {tab==='RESPONSE'&&<ResponsePanel selected={selected} score={score} onWarn={triggerSiren} onLog={logAction}/>} 
   {tab==='ANALYTICS'&&<AnalyticsPanel regions={regions} forecast={forecast}/>} 
  </main>
 </div>
}
function Ready({label,value}){return <div className="flex items-center justify-between"><span className="muted">{label}</span><span className="text-emerald-400 font-bold text-[9px] flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/>{value}</span></div>}
function WarningPanel({forecast,selected,score,onWarn}){return <div className="max-w-5xl mx-auto space-y-3"><section className="panel p-5"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><Badge critical={score>=75}>EARLY WARNING ENGINE</Badge><h2 className="text-2xl font-black text-white mt-3">{score >=75?'CRITICAL LANDSLIDE WATCH':'ENHANCED MONITORING'}</h2><p className="muted mt-2">{selected.name} · {selected.district}, {selected.state}</p></div><div className="text-left md:text-right"><p className={`text-5xl font-black ${riskClass(score)}`}>{score}</p><p className="muted">current risk index</p></div></div><div className="grid md:grid-cols-3 gap-3 mt-5"><div className="metric"><CloudRain/><b>135 mm</b><span>rainfall signal</span></div><div className="metric"><Zap/><b>84%</b><span>soil saturation proxy</span></div><div className="metric"><TrendingUp/><b>{selected.slope}°</b><span>terrain slope</span></div></div></section><section className="panel p-4"><h3 className="font-bold text-white">Risk escalation curve</h3><div className="h-72 mt-3"><ResponsiveContainer><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="time"/><YAxis/><Tooltip contentStyle={{background:'#0b1424',border:'1px solid #243244'}}/><Line dataKey="rain" name="Rainfall" stroke="#60a5fa" strokeWidth={2} dot={false}/><Line dataKey="risk" name="Risk" stroke="#f43f5e" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></section><button onClick={onWarn} className="w-full action danger py-4"><Bell className="w-5 h-5"/>Broadcast evacuation warning</button></div>}
function IncidentPanel({incidents,onField,onRefresh}){return <div className="max-w-6xl mx-auto"><div className="flex justify-between mb-3"><div><h2 className="text-xl font-black text-white">Incident Management</h2><p className="muted">Geo-tagged citizen and field-officer reports</p></div><div className="flex gap-2"><button onClick={onRefresh} className="action"><RefreshCw className="w-3 h-3"/>Refresh</button><button onClick={onField} className="action danger"><MapPin className="w-3 h-3"/>New report</button></div></div><div className="panel overflow-x-auto"><table className="w-full"><thead><tr className="text-left muted border-b border-slate-800"><th className="p-3">Incident</th><th>Severity</th><th>Location</th><th>Status</th><th>Time</th></tr></thead><tbody>{(incidents.length?incidents:[{id:'INC-DEMO-001',sector_name:'Bhalukpong - Bomdila Corridor',severity:'CRITICAL',lat:27.2645,lng:92.4159,status:'ACTIVE',timestamp:new Date().toISOString()},{id:'INC-DEMO-002',sector_name:'Sairang - Aizawl Syncline',severity:'HIGH',lat:23.7271,lng:92.7176,status:'MONITORING',timestamp:new Date().toISOString()}]).map(i=><tr key={i.id} className="border-b border-slate-800/70"><td className="p-3"><b>{i.sector_name||i.name}</b><small className="block muted">{i.type||'Field observation'}</small></td><td><span className={riskClass(i.severity==='CRITICAL'?90:i.severity==='HIGH'?70:45)}>{i.severity}</span></td><td className="font-mono text-[9px]">{Number(i.lat).toFixed(4)}, {Number(i.lng).toFixed(4)}</td><td><Badge>{i.status}</Badge></td><td className="muted text-[9px]">{new Date(i.timestamp).toLocaleString()}</td></tr>)}</tbody></table></div></div>}
function ResponsePanel({selected,score,onWarn,onLog}){return <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-3"><section className="panel p-5"><Badge critical={score>=75}>RESPONSE PRIORITY</Badge><h2 className="text-xl font-black text-white mt-3">{selected.name}</h2><p className="muted mt-1">{selected.district}, {selected.state}</p><div className="mt-5 space-y-3"><Ready label="Risk assessment" value={`${score}/100`}/><Ready label="Road control" value={selected.road_status}/><Ready label="Field team" value="DISPATCH READY"/><Ready label="Shelter coordination" value="READY"/></div></section><section className="panel p-5"><h3 className="font-bold text-white">Operational actions</h3><div className="grid gap-2 mt-4"><button onClick={()=>{onLog('NDRF_DISPATCH_REQUESTED');alert('Demo: NDRF dispatch request logged.')}} className="action"><Shield/>Request response team</button><button onClick={()=>{onLog('ROAD_CONTROL_REQUESTED');alert('Demo: road control action logged.')}} className="action"><Navigation/>Restrict affected corridor</button><button onClick={onWarn} className="action danger"><Siren/>Trigger evacuation warning</button><button onClick={()=>alert('Demo safe-corridor view: identify nearest verified shelter from district response database.')} className="action"><Users/>Open safe-corridor plan</button></div></section></div>}
function AnalyticsPanel({regions,forecast}){return <div className="max-w-6xl mx-auto space-y-3"><section className="grid md:grid-cols-4 gap-2">{regions.map(r=><div className="panel p-3" key={r.id}><p className="muted text-[9px]">{r.state}</p><b className="text-white block mt-1">{r.name}</b><p className={`text-2xl font-black mt-2 ${riskClass(riskScore(r))}`}>{riskScore(r)}</p><span className="muted">risk index</span></div>)}</section><section className="panel p-4"><h2 className="font-bold text-white">7-day operational trend</h2><div className="h-80 mt-3"><ResponsiveContainer><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="time"/><YAxis/><Tooltip contentStyle={{background:'#0b1424',border:'1px solid #243244'}}/><Line dataKey="risk" stroke="#22d3ee" strokeWidth={3}/><Line dataKey="rain" stroke="#60a5fa" strokeWidth={2}/></LineChart></ResponsiveContainer></div></section><section className="panel p-4"><h3 className="font-bold text-white">AI/ML readiness</h3><p className="muted mt-2">Current implementation uses an explainable weighted risk-fusion baseline. The API is intentionally model-ready for validated ML inference using rainfall, soil moisture, satellite-derived terrain features and historical landslide records. Do not present the baseline as a trained model until model weights and validation metrics are added.</p></section></div>}
