import React, { useEffect, useMemo, useState } from 'react';
import { MapContainer, TileLayer, CircleMarker, Polygon, Popup, useMap } from 'react-leaflet';
import { Activity, AlertTriangle, FileWarning, Navigation, Radio, RefreshCw, Siren, Users, Wind, Droplets, Thermometer, ShieldCheck, Wifi, WifiOff, Send, BellRing } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import FieldReporter from './FieldReporter';

const API = import.meta.env.VITE_API_URL || 'https://bhushakti-backend.onrender.com';
const DEMO_REGIONS = [
 {id:'GSI-AR-01',name:'Bhalukpong - Bomdila Corridor',district:'West Kameng',state:'Arunachal Pradesh',lat:27.2645,lng:92.4159,susceptibility:89,slope:46,elevation:2150,road:'NH-13',road_status:'CLOSED',rainfall_mm:168,soil_moisture_pct:88,temperature_c:22,humidity_pct:91,wind_kmh:14,population_at_risk:4200,forecast:[{time:'00:00',rain:38,risk:58},{time:'04:00',rain:72,risk:68},{time:'08:00',rain:128,risk:81},{time:'12:00',rain:168,risk:92},{time:'16:00',rain:140,risk:88},{time:'20:00',rain:96,risk:76}],villages:[{name:'Tenzingaon',distance_km:2.1,population:640},{name:'Nyukmadung',distance_km:3.4,population:520},{name:'Rama Camp Colony',distance_km:5.8,population:310}]},
 {id:'GSI-AR-02',name:'Tawang - Bomdila Corridor',district:'Tawang',state:'Arunachal Pradesh',lat:27.5867,lng:91.859,susceptibility:86,slope:43,elevation:2650,road:'NH-13',road_status:'RESTRICTED',rainfall_mm:142,soil_moisture_pct:82,temperature_c:14,humidity_pct:86,wind_kmh:18,population_at_risk:2900,forecast:[],villages:[{name:'Dirang',distance_km:3,population:780},{name:'Jang',distance_km:5.1,population:460}]},
 {id:'GSI-AR-03',name:'Itanagar - Naharlagun Corridor',district:'Papum Pare',state:'Arunachal Pradesh',lat:27.102,lng:93.695,susceptibility:72,slope:29,elevation:440,road:'NH-15',road_status:'OPEN',rainfall_mm:116,soil_moisture_pct:76,temperature_c:27,humidity_pct:84,wind_kmh:8,population_at_risk:6100,forecast:[],villages:[{name:'Naharlagun',distance_km:2,population:1400},{name:'Doimukh',distance_km:5.4,population:820}]},
 {id:'GSI-AS-01',name:'Haflong - Silchar Corridor',district:'Dima Hasao',state:'Assam',lat:25.164,lng:93.0176,susceptibility:79,slope:34,elevation:680,road:'NH-27',road_status:'RESTRICTED',rainfall_mm:154,soil_moisture_pct:87,temperature_c:24,humidity_pct:90,wind_kmh:10,population_at_risk:3500,forecast:[],villages:[{name:'Mahur',distance_km:2.5,population:510},{name:'Jatinga',distance_km:4.7,population:380}]},
 {id:'GSI-ML-01',name:'Cherrapunji - Mawsynram Escarpment',district:'East Khasi Hills',state:'Meghalaya',lat:25.2986,lng:91.5822,susceptibility:81,slope:38,elevation:1430,road:'SH-5',road_status:'RESTRICTED',rainfall_mm:205,soil_moisture_pct:92,temperature_c:20,humidity_pct:95,wind_kmh:11,population_at_risk:3100,forecast:[],villages:[{name:'Mawkdok',distance_km:1.8,population:410},{name:'Nongriat approach hamlet',distance_km:4.2,population:180},{name:'Laitkynsew',distance_km:6.5,population:390}]},
 {id:'GSI-ML-02',name:'Shillong - Jowai Corridor',district:'East Khasi Hills / West Jaintia Hills',state:'Meghalaya',lat:25.467,lng:92.203,susceptibility:74,slope:33,elevation:1250,road:'NH-6',road_status:'OPEN',rainfall_mm:132,soil_moisture_pct:80,temperature_c:19,humidity_pct:88,wind_kmh:9,population_at_risk:4700,forecast:[],villages:[{name:'Mawphlang',distance_km:3.1,population:620},{name:'Nartiang',distance_km:6,population:560}]},
 {id:'GSI-MZ-01',name:'Sairang - Aizawl Syncline',district:'Aizawl',state:'Mizoram',lat:23.7271,lng:92.7176,susceptibility:84,slope:35,elevation:1132,road:'NH-54',road_status:'CLOSED',rainfall_mm:149,soil_moisture_pct:86,temperature_c:23,humidity_pct:89,wind_kmh:13,population_at_risk:3800,forecast:[],villages:[{name:'Sairang Venglai',distance_km:1.2,population:710},{name:'Sialsuk',distance_km:3.9,population:340},{name:'Tuirial',distance_km:6,population:410}]},
 {id:'GSI-MZ-02',name:'Lunglei Corridor',district:'Lunglei',state:'Mizoram',lat:22.8877,lng:92.738,susceptibility:78,slope:37,elevation:1220,road:'NH-302',road_status:'RESTRICTED',rainfall_mm:137,soil_moisture_pct:83,temperature_c:22,humidity_pct:90,wind_kmh:12,population_at_risk:2500,forecast:[],villages:[{name:'Hnahthial',distance_km:3.4,population:480},{name:'Lungsen',distance_km:5.2,population:360}]},
 {id:'GSI-NL-01',name:'Pfutsero - Kohima Ridge',district:'Kohima',state:'Nagaland',lat:25.6751,lng:94.1086,susceptibility:76,slope:32,elevation:1444,road:'NH-29',road_status:'RESTRICTED',rainfall_mm:98,soil_moisture_pct:70,temperature_c:19,humidity_pct:82,wind_kmh:9,population_at_risk:2600,forecast:[],villages:[{name:'Chizami',distance_km:3,population:450},{name:'Losami',distance_km:4.6,population:300},{name:'Kikruma',distance_km:7.1,population:520}]},
 {id:'GSI-MN-01',name:'Ukhrul - Imphal Corridor',district:'Ukhrul / Imphal East',state:'Manipur',lat:24.75,lng:94.01,susceptibility:77,slope:36,elevation:1120,road:'NH-202',road_status:'RESTRICTED',rainfall_mm:128,soil_moisture_pct:81,temperature_c:21,humidity_pct:86,wind_kmh:10,population_at_risk:3300,forecast:[],villages:[{name:'Hundung',distance_km:2.7,population:430},{name:'Sikhong',distance_km:5.5,population:350}]},
 {id:'GSI-SK-01',name:'Gangtok - Rangpo Corridor',district:'Gangtok / Pakyong',state:'Sikkim',lat:27.3389,lng:88.6065,susceptibility:88,slope:44,elevation:1650,road:'NH-10',road_status:'CLOSED',rainfall_mm:176,soil_moisture_pct:89,temperature_c:18,humidity_pct:92,wind_kmh:15,population_at_risk:5200,forecast:[],villages:[{name:'Rangpo',distance_km:1.9,population:950},{name:'Singtam',distance_km:4,population:720}]},
];
const riskScore=r=>r.risk_score??Math.min(100,Math.round(r.susceptibility*.45+Math.min((r.rainfall_mm||135)/150*100,100)*.25+(r.soil_moisture_pct||84)*.15+Math.min(r.slope/50*100,100)*.15));
const riskLevel=n=>n>=75?'CRITICAL':n>=55?'HIGH':n>=35?'MODERATE':'LOW';
const riskTone=n=>n>=75?'red':n>=55?'amber':'emerald';
const riskClass=n=>({red:'text-red-400',amber:'text-amber-400',emerald:'text-emerald-400'}[riskTone(n)]);
const villageRisk=(parent,distance)=>Math.max(20,Math.min(100,Math.round(parent-distance*4)));
function FlyTo({region}){const map=useMap();useEffect(()=>{map.flyTo([region.lat,region.lng],8,{duration:.8})},[region,map]);return null}
function Stat({icon:Icon,label,value,sub,tone='cyan'}){const iconClass={cyan:'text-cyan-400',red:'text-red-400',amber:'text-amber-400',emerald:'text-emerald-400'}[tone]||'text-cyan-400';return <div className="panel p-3"><div className="flex items-center justify-between"><div><p className="muted uppercase tracking-widest text-[9px]">{label}</p><p className="text-xl font-black text-white mt-1">{value}</p><p className="muted text-[9px] mt-1">{sub}</p></div><Icon className={`w-5 h-5 ${iconClass}`}/></div></div>}
function Badge({children,critical=false}){return <span className={`px-2 py-1 rounded-md text-[9px] font-black tracking-wider ${critical?'bg-red-500/15 text-red-400 border border-red-500/30':'bg-cyan-500/10 text-cyan-300 border border-cyan-500/20'}`}>{children}</span>}

export default function App(){
 const [regions,setRegions]=useState(DEMO_REGIONS);const [selected,setSelected]=useState(DEMO_REGIONS[0]);const [incidents,setIncidents]=useState([]);const [summary,setSummary]=useState(null);const [alerts,setAlerts]=useState([]);const [recipients,setRecipients]=useState([]);const [tab,setTab]=useState('COMMAND');const [field,setField]=useState(false);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [siren,setSiren]=useState(false);const [online,setOnline]=useState(navigator.onLine);const [alertSending,setAlertSending]=useState(false);
 const load=async()=>{setLoading(true);try{const[r,s,i,a,u]=await Promise.all([fetch(`${API}/api/regions`),fetch(`${API}/api/dashboard/summary`),fetch(`${API}/api/incidents`),fetch(`${API}/api/alerts`),fetch(`${API}/api/recipients`)]);if(r.ok){const data=await r.json();setRegions(data);const first=data.find(x=>x.id===selected.id)||data[0];if(first)setSelected(first)}if(s.ok)setSummary(await s.json());if(i.ok)setIncidents(await i.json());if(a.ok)setAlerts(await a.json());if(u.ok)setRecipients(await u.json());setNotice('API CONNECTED · DEMO RISK INPUTS')}catch{setNotice('DEMO MODE · API UNAVAILABLE')}finally{setLoading(false)}};
 useEffect(()=>{load();const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener('online',up);window.addEventListener('offline',down);return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down)}},[]);
 const score=useMemo(()=>riskScore(selected),[selected]);const level=riskLevel(score);const forecast=selected.forecast?.length?selected.forecast:[{time:'00:00',rain:Math.round(selected.rainfall_mm*.25),risk:Math.max(25,score-20)},{time:'04:00',rain:Math.round(selected.rainfall_mm*.45),risk:Math.max(30,score-12)},{time:'08:00',rain:Math.round(selected.rainfall_mm*.72),risk:Math.max(35,score-5)},{time:'12:00',rain:selected.rainfall_mm,risk:score},{time:'16:00',rain:Math.round(selected.rainfall_mm*.83),risk:Math.max(30,score-5)},{time:'20:00',rain:Math.round(selected.rainfall_mm*.57),risk:Math.max(25,score-12)}];
 const villages=useMemo(()=>[...(selected.villages||[])].map(v=>({...v,risk_score:v.risk_score??villageRisk(score,v.distance_km),risk_level:riskLevel(v.risk_score??villageRisk(score,v.distance_km))})).sort((a,b)=>b.risk_score-a.risk_score),[selected,score]);
 const priority=score>=85?{title:'IMMEDIATE RESPONSE',action:'Restrict corridor + prepare evacuation',detail:'Alert priority villages and deploy field team.'}:score>=75?{title:'HIGH PRIORITY',action:'Deploy field team + restrict traffic',detail:'Increase monitoring and prepare shelters.'}:score>=55?{title:'ENHANCED MONITORING',action:'Increase sensor observation',detail:'Keep response team on standby.'}:{title:'ROUTINE WATCH',action:'Continue scheduled monitoring',detail:'No immediate evacuation indicated.'};
 const critical=regions.filter(r=>riskScore(r)>=75).length;const high=regions.filter(r=>riskScore(r)>=55&&riskScore(r)<75).length;const lastAlert=alerts[0];
 const logAction=async action=>{try{await fetch(`${API}/api/log-action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sector_name:selected.name,lat:selected.lat,lng:selected.lng,risk_score:score,action_triggered:action,extra_data:{weather:{rainfall_mm:selected.rainfall_mm,soil_moisture_pct:selected.soil_moisture_pct}}})})}catch{}};
 const triggerSiren=()=>{setSiren(true);logAction('EVACUATION_WARNING_TRIGGERED');setNotice('WARNING MODE ACTIVE · DEMO DELIVERY');if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`Landslide warning. ${level} risk at ${selected.name}. Follow official evacuation instructions.`))}};
 const sendAlert=async()=>{setAlertSending(true);const message=`BHUSAKTHI ALERT: ${level} landslide risk at ${selected.name}. Avoid ${selected.road} near the affected zone and follow local administration instructions.`;try{const r=await fetch(`${API}/api/alerts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region_id:selected.id,severity:level,message,channels:['DASHBOARD','SMS']})});if(!r.ok)throw new Error();const data=await r.json();await fetch(`${API}/api/alerts/${data.alert.id}/dispatch`,{method:'POST'});setNotice(`ALERT DISPATCHED · ${data.alert.recipient_count||0} REGISTERED RECIPIENTS · SIMULATED SMS`);load()}catch{setNotice('ALERT QUEUED LOCALLY · NETWORK REQUIRED FOR SERVER DELIVERY')}finally{setAlertSending(false)}};
 const submitReport=rep=>{setIncidents(x=>[rep,...x]);setField(false);setNotice('FIELD REPORT RECEIVED · MAP UPDATED');load()};
 const tabs=[['COMMAND','Command'],['GIS','Live GIS'],['WARNING','Early Warning'],['INCIDENTS','Incidents'],['RESPONSE','Response'],['ANALYTICS','Analytics']];
 const rt=riskTone(score);const riskBar=rt==='red'?'bg-red-500':rt==='amber'?'bg-amber-400':'bg-emerald-500';
 return <div className="h-screen w-screen overflow-hidden bg-[#050a13] text-slate-200 text-xs font-sans">{field&&<FieldReporter onBack={()=>setField(false)} onReportSubmitted={submitReport}/>} {siren&&<div className="fixed inset-0 z-[3000] bg-red-950/90 backdrop-blur flex items-center justify-center p-6"><div className="max-w-md w-full panel border-red-500 p-7 text-center shadow-2xl shadow-red-950"><div className="mx-auto w-16 h-16 rounded-full bg-red-500/20 flex items-center justify-center animate-pulse"><Siren className="w-8 h-8 text-red-400"/></div><h2 className="text-2xl font-black text-red-300 mt-4">EVACUATION WARNING</h2><p className="text-slate-300 mt-2">{selected.name}</p><p className="text-5xl font-black text-white mt-3">{score}<span className="text-xl">/100</span></p><p className="text-red-300 text-[10px] uppercase tracking-widest mt-2">{priority.action}</p><button onClick={()=>setSiren(false)} className="mt-6 px-5 py-2 bg-red-600 rounded-lg font-bold">ACKNOWLEDGE</button></div></div>}
 <header className="h-14 border-b border-slate-800 bg-[#080f1d] flex items-center justify-between px-4 gap-4"><div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 rounded-lg bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center"><Activity className="w-5 h-5 text-cyan-400"/></div><div className="min-w-0"><h1 className="font-black tracking-widest text-white text-sm">BHUSAKTHI</h1><p className="muted text-[8px] uppercase tracking-[.25em] truncate">AI Landslide Early Warning & Response · NER</p></div></div><div className="hidden md:flex items-center gap-1">{tabs.map(([id,name])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-md text-[9px] font-bold uppercase tracking-wider ${tab===id?'bg-cyan-500/15 text-cyan-300':'text-slate-500 hover:text-white'}`}>{name}</button>)}</div><div className="flex items-center gap-2"><span className={`hidden sm:flex items-center gap-1 text-[9px] ${online?'text-emerald-400':'text-amber-400'}`}>{online?<Wifi className="w-3 h-3"/>:<WifiOff className="w-3 h-3"/>}{online?'NETWORK ONLINE':'OFFLINE QUEUE'}</span><button onClick={load} className="p-2 hover:bg-slate-800 rounded"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div></header>
 <main className="h-[calc(100vh-56px)] overflow-auto p-3 md:p-4"><div className="mb-3 rounded-xl border border-cyan-500/20 bg-gradient-to-r from-cyan-500/10 via-blue-500/5 to-transparent p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-2"><div><p className="text-[10px] font-black tracking-[.18em] text-cyan-300">NER 11-ZONE PILOT NETWORK</p><p className="text-[9px] text-slate-400 mt-1">Risk engine status: <b className="text-amber-300">DEMO INPUTS · API READY</b> · not a verified live hazard bulletin</p></div><Badge>{regions.length} ZONES · {recipients.length} REGISTERED</Badge></div>
 {tab==='COMMAND'&&<>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-2 mb-3"><Stat icon={AlertTriangle} label="Critical zones" value={critical} sub="Immediate attention" tone="red"/><Stat icon={Activity} label="High risk zones" value={high} sub="Enhanced monitoring" tone="amber"/><Stat icon={FileWarning} label="Active incidents" value={incidents.filter(i=>i.status!=='RESOLVED').length||0} sub="Field + system reports"/><Stat icon={Radio} label="Sensors online" value={summary?.sensors_online||12} sub="Demo telemetry"/><Stat icon={Navigation} label="Roads impacted" value={summary?.roads_impacted||0} sub="Closed / restricted" tone="amber"/></div>
  <div className="grid xl:grid-cols-[1.55fr_1fr] gap-3"><section className="panel overflow-hidden"><div className="px-3 py-2 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold text-white">Regional Risk Map</h2><p className="muted text-[9px]">11 selected pilot zones · click a zone to refresh intelligence</p></div><Badge>{regions.length} MONITORED ZONES</Badge></div><div className="h-[330px] md:h-[430px] relative"><MapContainer center={[25.7,92.8]} zoom={6} scrollWheelZoom className="h-full w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FlyTo region={selected}/>{regions.map(r=>{const s=r.risk_score??riskScore(r);const color=s>=75?'#ef4444':s>=55?'#f59e0b':'#10b981';return <React.Fragment key={r.id}><Polygon positions={[[r.lat+.12,r.lng-.12],[r.lat+.12,r.lng+.12],[r.lat-.12,r.lng+.12],[r.lat-.12,r.lng-.12]]} pathOptions={{color,fillColor:color,fillOpacity:.13,weight:r.id===selected.id?3:1}}/><CircleMarker center={[r.lat,r.lng]} radius={r.id===selected.id?14:s>=75?11:8} pathOptions={{color,fillColor:color,fillOpacity:.8}} eventHandlers={{click:()=>setSelected(r)}}><Popup><b>{r.name}</b><br/>Risk: {s}/100 · {riskLevel(s)}<br/>Rainfall: {r.rainfall_mm??'—'} mm<br/>{r.road}: {r.road_status}</Popup></CircleMarker></React.Fragment>)})}</MapContainer><div className="absolute top-3 left-3 z-[500] panel px-3 py-2 pointer-events-none"><p className="text-[8px] text-cyan-300 font-bold">GIS RISK OVERLAY</p><p className="text-[8px] muted">RED critical · AMBER high · GREEN monitored</p></div><div className="absolute bottom-3 right-3 z-[500] panel px-3 py-2 pointer-events-none text-[8px] space-y-1"><p><span className="inline-block w-2 h-2 rounded-full bg-red-500 mr-1"/>CRITICAL ≥75</p><p><span className="inline-block w-2 h-2 rounded-full bg-amber-400 mr-1"/>HIGH 55–74</p><p><span className="inline-block w-2 h-2 rounded-full bg-emerald-500 mr-1"/>MONITORED &lt;55</p></div></div></section>
   <div className="space-y-3"><section className={`panel p-4 border-${rt}-500/30 bg-gradient-to-br from-${rt}-500/10 to-transparent`}><div className="flex items-start justify-between"><div><p className="muted text-[9px] uppercase tracking-widest">Selected zone · {selected.state}</p><h2 className="text-base font-black text-white mt-1">{selected.name}</h2></div><Badge critical={score>=75}>{level}</Badge></div><div className="flex items-end gap-3 mt-4"><p className={`text-6xl font-black ${riskClass(score)}`}>{score}</p><div className="pb-2"><p className="text-slate-400 text-[9px]">AI RISK SCORE</p><p className="text-white font-bold">{priority.title}</p></div></div><div className="mt-3 h-2 rounded-full bg-slate-800 overflow-hidden"><div className={`h-full ${riskBar} rounded-full`} style={{width:`${score}%`}}/></div><div className="grid grid-cols-3 gap-2 mt-4"><div><p className="muted text-[8px]">RAINFALL</p><p className="font-bold text-white">{selected.rainfall_mm} mm</p></div><div><p className="muted text-[8px]">SOIL MOISTURE</p><p className="font-bold text-white">{selected.soil_moisture_pct}%</p></div><div><p className="muted text-[8px]">SLOPE</p><p className="font-bold text-white">{selected.slope}°</p></div></div></section>
    <section className="panel p-3"><div className="flex items-center justify-between mb-2"><h3 className="font-bold text-white">Risk → Reason → Action</h3><ShieldCheck className={`w-4 h-4 ${riskClass(score)}`}/></div><p className="text-[10px] text-slate-300">Multiple terrain and weather indicators are fused by the transparent baseline risk engine.</p><div className="mt-2 text-[10px] space-y-1"><p>• Susceptibility: <b>{selected.susceptibility}</b></p><p>• Rainfall pressure: <b>{selected.rainfall_mm} mm</b></p><p>• Soil saturation: <b>{selected.soil_moisture_pct}%</b></p></div><p className="mt-2 text-amber-300 font-bold text-[10px]">ACTION: {priority.action}</p><p className="muted text-[9px]">{priority.detail}</p></section>
    <section className="panel p-3"><div className="flex items-center justify-between"><div><h3 className="font-bold text-white">6-Hour Forecast Window</h3><p className="muted text-[8px]">Demo forecast until IMD API is connected</p></div><CloudRainIcon/></div><div className="h-28 mt-2"><ResponsiveContainer width="100%" height="100%"><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="time" tick={{fontSize:8,fill:'#64748b'}}/><YAxis tick={{fontSize:8,fill:'#64748b'}} domain={[0,100]}/><Tooltip contentStyle={{background:'#0b1527',border:'1px solid #1e293b',fontSize:10}}/><Line type="monotone" dataKey="risk" stroke="#ef4444" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></section></div>
  </div>
  <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-3 mt-3"><section className="panel p-3"><div className="flex items-center justify-between mb-2"><h3 className="font-bold text-white">Priority Villages</h3><Users className="w-4 h-4 text-cyan-400"/></div><div className="space-y-2">{villages.map(v=><div key={v.name} className="flex items-center justify-between rounded-lg bg-slate-900/60 border border-slate-800 p-2"><div><p className="font-bold text-slate-200">{v.name}</p><p className="muted text-[8px]">{v.distance_km} km · population {v.population}</p></div><span className={`font-black ${riskClass(v.risk_score)}`}>{v.risk_score} · {v.risk_level}</span></div>)}</div></section><section className="panel p-3"><div className="flex items-center gap-2 mb-2"><BellRing className="w-4 h-4 text-red-400"/><h3 className="font-bold text-white">Alert Center</h3></div><p className="muted text-[9px]">Registered SMS recipients: <b className="text-white">{recipients.length}</b></p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={sendAlert} disabled={alertSending} className="py-2 rounded-lg bg-red-600 hover:bg-red-500 disabled:opacity-50 font-black flex items-center justify-center gap-2"><Send className="w-3.5 h-3.5"/>{alertSending?'DISPATCHING':'SEND WARNING'}</button><button onClick={triggerSiren} className="py-2 rounded-lg border border-red-500/40 text-red-300 font-black flex items-center justify-center gap-2"><Siren className="w-3.5 h-3.5"/>WARNING MODE</button></div>{lastAlert&&<p className="mt-2 text-[8px] text-emerald-400">Last alert: {lastAlert.status} · {lastAlert.delivered_count||0}/{lastAlert.recipient_count||0} simulated SMS</p>}</section></div>
 </>}
 {tab==='GIS'&&<section className="panel p-3"><h2 className="font-black text-white text-lg">Live GIS Intelligence</h2><p className="muted mt-1">Selected pilot zones are intentionally compact so the application does not require loading a massive raw raster/satellite archive into the browser.</p><div className="mt-3 grid md:grid-cols-3 gap-2">{regions.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="text-left panel p-3 hover:border-cyan-500/50"><p className="font-bold text-white">{r.name}</p><p className={`text-xl font-black mt-1 ${riskClass(riskScore(r))}`}>{riskScore(r)}</p><p className="muted text-[8px]">{r.state} · {r.road_status}</p></button>)}</div></section>}
 {tab==='WARNING'&&<section className="panel p-4"><h2 className="font-black text-white text-lg">Early Warning & Alert Operations</h2><p className="muted mt-1">Warnings are clearly marked as simulated until an approved SMS provider and live data feeds are configured.</p><div className="mt-4 grid md:grid-cols-3 gap-3"><div className="panel p-4 border-red-500/30"><Siren className="text-red-400"/><p className="font-black mt-2">CRITICAL WARNING</p><p className="muted text-[9px] mt-1">For score ≥75: restrict exposed corridor, alert nearby communities, deploy field team.</p><button onClick={triggerSiren} className="mt-3 w-full py-2 bg-red-600 rounded font-bold">OPEN WARNING SCREEN</button></div><div className="panel p-4"><Users className="text-cyan-400"/><p className="font-black mt-2">REGISTERED RECIPIENTS</p><p className="text-3xl font-black text-white mt-1">{recipients.length}</p><p className="muted text-[9px]">Region-specific SMS targets</p></div><div className="panel p-4"><Send className="text-amber-400"/><p className="font-black mt-2">LAST DISPATCH</p><p className="text-lg font-black text-white mt-1">{lastAlert?.status||'NO ALERTS'}</p><p className="muted text-[9px]">Delivery provider: simulated</p></div></div><div className="mt-4 panel p-3"><h3 className="font-bold text-white">Recommended message</h3><p className="mt-2 text-[11px] text-slate-300">⚠️ BHUSAKTHI ALERT — {level} landslide risk detected for {selected.name}. Avoid {selected.road} near the affected zone. Follow local administration instructions.</p></div></section>}
 {tab==='INCIDENTS'&&<section className="panel p-3"><div className="flex justify-between items-center"><h2 className="font-black text-white text-lg">Incident Command Log</h2><button onClick={()=>setField(true)} className="px-3 py-2 bg-cyan-600 rounded font-bold">+ FIELD REPORT</button></div><div className="mt-3 space-y-2">{incidents.map(i=><div key={i.id} className="border border-slate-800 rounded-lg p-3"><div className="flex justify-between gap-3"><div><p className="font-bold text-white">{i.sector_name}</p><p className="muted text-[9px]">{i.type} · {i.timestamp}</p></div><Badge critical={i.severity==='CRITICAL'}>{i.severity}</Badge></div><p className="text-[10px] text-slate-300 mt-2">{i.notes}</p></div>)}</div></section>}
 {tab==='RESPONSE'&&<section className="panel p-4"><h2 className="font-black text-white text-lg">Emergency Response Prioritisation</h2><div className="mt-3 space-y-2">{[...regions].sort((a,b)=>riskScore(b)-riskScore(a)).map((r,idx)=><div key={r.id} className="flex items-center gap-3 border border-slate-800 rounded-lg p-3"><span className="w-7 h-7 rounded-full bg-slate-800 flex items-center justify-center font-black">{idx+1}</span><div className="flex-1"><p className="font-bold text-white">{r.name}</p><p className="muted text-[8px]">{r.state} · {r.road} · {r.road_status}</p></div><span className={`text-xl font-black ${riskClass(riskScore(r))}`}>{riskScore(r)}</span></div>)}</div></section>}
 {tab==='ANALYTICS'&&<section className="panel p-4"><h2 className="font-black text-white text-lg">Model & Data Analytics</h2><div className="mt-3 grid md:grid-cols-4 gap-2"><Stat icon={Droplets} label="Rainfall" value={`${selected.rainfall_mm} mm`} sub="Demo input"/><Stat icon={Thermometer} label="Temperature" value={`${selected.temperature_c}°C`} sub="Demo input"/><Stat icon={Wind} label="Wind" value={`${selected.wind_kmh} km/h`} sub="Demo input"/><Stat icon={Users} label="Exposure" value={selected.population_at_risk||0} sub="Population proxy"/></div><div className="mt-3 panel p-3"><p className="font-bold text-white">Compact feature strategy</p><p className="muted text-[10px] mt-1">Raw satellite/raster archives stay outside the browser. BHUSAKTHI consumes compact features such as rainfall, soil moisture, slope, elevation, susceptibility, historical density and satellite-change indicators. This keeps GPU/storage requirements manageable for an 11-zone pilot.</p></div></section>}
 <div className="mt-3 flex flex-wrap gap-2 items-center"><button onClick={()=>setField(true)} className="px-3 py-2 bg-cyan-600 hover:bg-cyan-500 rounded-lg font-bold flex items-center gap-2"><Navigation className="w-3.5 h-3.5"/>FIELD REPORT</button><button onClick={sendAlert} disabled={alertSending} className="px-3 py-2 bg-red-600 hover:bg-red-500 rounded-lg font-bold flex items-center gap-2"><Send className="w-3.5 h-3.5"/>SEND WARNING</button><span className="muted text-[9px]">Data source: {summary?.data_mode||'DEMO INPUTS'} · Risk source: {selected.risk_source||'DEMO_WEIGHTED_BASELINE'}</span></div></main></div>
}
function CloudRainIcon(){return <span className="text-cyan-400">☁︎</span>}
